# Generated by Django 5.0.7 on 2024-07-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Customers", "0001_initial"),
        ("Orders", "0001_initial"),
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="Customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="Products.product",
            ),
        ),
    ]
